name: CI

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]

jobs:
  selene:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rokit
        uses: CompeyDev/setup-rokit@v0.1.2
        with:
          cache: true

      - name: Run Selene
        run: selene src/

  stylua:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rokit
        uses: CompeyDev/setup-rokit@v0.1.2
        with:
          cache: true

      - name: Run Stylua
        run: stylua --check src/

